[package]
name = "vk_commander"
version = "0.0.10"
edition = "2024"
rust-version = "1.90"
authors = ["Benjamin Oswald"]
license = "AGPL-3.0"
repository = "https://github.com/ben-oswald/vk_commander"
homepage = "https://oswald.dev"
build = "build.rs"

[dependencies]
ssh2 = "0.9"
egui = "0.33.3"
egui_code_editor = { version = "0.2.20", features = ["serde"] }
egui_extras = "0.33.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
image = { version = "0.25.9", default-features = false, features = ["png"] }
vk_macros = { path = "packages/vk_macros" }
    egui-file-dialog = "0.12.0"
csv = "1.4"


[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.33.3", features = ["default_fonts", "glow", "wayland"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
eframe = { version = "0.33", features = ["default_fonts", "wgpu"] }
wgpu = { version = "27.0.1", features = ["dx12", "vulkan", "gles"] }

[build-dependencies]
embed-resource = "3.0.6"

[profile.release]
strip = true
lto = "thin"
opt-level = "z"
codegen-units = 1
panic = "abort"
